// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AstrisNodeClient is the client API for AstrisNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AstrisNodeClient interface {
	// Obtain a list of peers to connect to, of course we
	// must seed some peers first...
	GetPeers(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (AstrisNode_GetPeersClient, error)
	// this is the connection we open to receive blocks
	// we only have a recieve function. If other peers
	// want blocks from us, they must call RecieveBlocks
	// to open the channel
	// We pass an ElectionId and assume all blocks on the channel
	// are for the given election. If the server does not support
	// this election, they SHOULD end the stream immediately
	RecieveBlocks(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (AstrisNode_RecieveBlocksClient, error)
	// recieve a specific block from the peer, if they have it
	// this can be used to populate your chain
	// this is irrespective of ElectionID as all the blocks are uniquely
	// addressed.
	FetchBlock(ctx context.Context, in *BlockID, opts ...grpc.CallOption) (*FullBlock, error)
	// get the block the peer considers to be the top of the current confirmed chain
	// we may have recieved more valid blocks than this, and we maintain a few speculative
	// chains, but once X peers have confirmed the block it is considered valid and the
	// longest chain wins.
	Head(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (*BlockHeader, error)
}

type astrisNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewAstrisNodeClient(cc grpc.ClientConnInterface) AstrisNodeClient {
	return &astrisNodeClient{cc}
}

func (c *astrisNodeClient) GetPeers(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (AstrisNode_GetPeersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AstrisNode_serviceDesc.Streams[0], "/astris.AstrisNode/GetPeers", opts...)
	if err != nil {
		return nil, err
	}
	x := &astrisNodeGetPeersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AstrisNode_GetPeersClient interface {
	Recv() (*Peer, error)
	grpc.ClientStream
}

type astrisNodeGetPeersClient struct {
	grpc.ClientStream
}

func (x *astrisNodeGetPeersClient) Recv() (*Peer, error) {
	m := new(Peer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *astrisNodeClient) RecieveBlocks(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (AstrisNode_RecieveBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AstrisNode_serviceDesc.Streams[1], "/astris.AstrisNode/RecieveBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &astrisNodeRecieveBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AstrisNode_RecieveBlocksClient interface {
	Recv() (*BlockHeader, error)
	grpc.ClientStream
}

type astrisNodeRecieveBlocksClient struct {
	grpc.ClientStream
}

func (x *astrisNodeRecieveBlocksClient) Recv() (*BlockHeader, error) {
	m := new(BlockHeader)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *astrisNodeClient) FetchBlock(ctx context.Context, in *BlockID, opts ...grpc.CallOption) (*FullBlock, error) {
	out := new(FullBlock)
	err := c.cc.Invoke(ctx, "/astris.AstrisNode/FetchBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *astrisNodeClient) Head(ctx context.Context, in *ElectionID, opts ...grpc.CallOption) (*BlockHeader, error) {
	out := new(BlockHeader)
	err := c.cc.Invoke(ctx, "/astris.AstrisNode/Head", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AstrisNodeServer is the server API for AstrisNode service.
// All implementations must embed UnimplementedAstrisNodeServer
// for forward compatibility
type AstrisNodeServer interface {
	// Obtain a list of peers to connect to, of course we
	// must seed some peers first...
	GetPeers(*ElectionID, AstrisNode_GetPeersServer) error
	// this is the connection we open to receive blocks
	// we only have a recieve function. If other peers
	// want blocks from us, they must call RecieveBlocks
	// to open the channel
	// We pass an ElectionId and assume all blocks on the channel
	// are for the given election. If the server does not support
	// this election, they SHOULD end the stream immediately
	RecieveBlocks(*ElectionID, AstrisNode_RecieveBlocksServer) error
	// recieve a specific block from the peer, if they have it
	// this can be used to populate your chain
	// this is irrespective of ElectionID as all the blocks are uniquely
	// addressed.
	FetchBlock(context.Context, *BlockID) (*FullBlock, error)
	// get the block the peer considers to be the top of the current confirmed chain
	// we may have recieved more valid blocks than this, and we maintain a few speculative
	// chains, but once X peers have confirmed the block it is considered valid and the
	// longest chain wins.
	Head(context.Context, *ElectionID) (*BlockHeader, error)
	mustEmbedUnimplementedAstrisNodeServer()
}

// UnimplementedAstrisNodeServer must be embedded to have forward compatible implementations.
type UnimplementedAstrisNodeServer struct {
}

func (UnimplementedAstrisNodeServer) GetPeers(*ElectionID, AstrisNode_GetPeersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedAstrisNodeServer) RecieveBlocks(*ElectionID, AstrisNode_RecieveBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method RecieveBlocks not implemented")
}
func (UnimplementedAstrisNodeServer) FetchBlock(context.Context, *BlockID) (*FullBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBlock not implemented")
}
func (UnimplementedAstrisNodeServer) Head(context.Context, *ElectionID) (*BlockHeader, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Head not implemented")
}
func (UnimplementedAstrisNodeServer) mustEmbedUnimplementedAstrisNodeServer() {}

// UnsafeAstrisNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AstrisNodeServer will
// result in compilation errors.
type UnsafeAstrisNodeServer interface {
	mustEmbedUnimplementedAstrisNodeServer()
}

func RegisterAstrisNodeServer(s grpc.ServiceRegistrar, srv AstrisNodeServer) {
	s.RegisterService(&_AstrisNode_serviceDesc, srv)
}

func _AstrisNode_GetPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ElectionID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AstrisNodeServer).GetPeers(m, &astrisNodeGetPeersServer{stream})
}

type AstrisNode_GetPeersServer interface {
	Send(*Peer) error
	grpc.ServerStream
}

type astrisNodeGetPeersServer struct {
	grpc.ServerStream
}

func (x *astrisNodeGetPeersServer) Send(m *Peer) error {
	return x.ServerStream.SendMsg(m)
}

func _AstrisNode_RecieveBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ElectionID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AstrisNodeServer).RecieveBlocks(m, &astrisNodeRecieveBlocksServer{stream})
}

type AstrisNode_RecieveBlocksServer interface {
	Send(*BlockHeader) error
	grpc.ServerStream
}

type astrisNodeRecieveBlocksServer struct {
	grpc.ServerStream
}

func (x *astrisNodeRecieveBlocksServer) Send(m *BlockHeader) error {
	return x.ServerStream.SendMsg(m)
}

func _AstrisNode_FetchBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AstrisNodeServer).FetchBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astris.AstrisNode/FetchBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AstrisNodeServer).FetchBlock(ctx, req.(*BlockID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AstrisNode_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AstrisNodeServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astris.AstrisNode/Head",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AstrisNodeServer).Head(ctx, req.(*ElectionID))
	}
	return interceptor(ctx, in, info, handler)
}

var _AstrisNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "astris.AstrisNode",
	HandlerType: (*AstrisNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchBlock",
			Handler:    _AstrisNode_FetchBlock_Handler,
		},
		{
			MethodName: "Head",
			Handler:    _AstrisNode_Head_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPeers",
			Handler:       _AstrisNode_GetPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecieveBlocks",
			Handler:       _AstrisNode_RecieveBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol/astris.proto",
}
