// Code generated by "stringer -type=PayloadHint"; DO NOT EDIT.

package astris

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HintUnknown-0]
	_ = x[HintElectionSetup-1]
	_ = x[HintTrusteeShares-2]
	_ = x[HintTrusteePublic-3]
	_ = x[HintVoterReg-4]
	_ = x[HintBallot-5]
	_ = x[HintPartialTally-6]
}

const _PayloadHint_name = "HintUnknownHintElectionSetupHintTrusteeSharesHintTrusteePublicHintVoterRegHintBallotHintPartialTally"

var _PayloadHint_index = [...]uint8{0, 11, 28, 45, 62, 74, 84, 100}

func (i PayloadHint) String() string {
	if i >= PayloadHint(len(_PayloadHint_index)-1) {
		return "PayloadHint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PayloadHint_name[_PayloadHint_index[i]:_PayloadHint_index[i+1]]
}
